# Pre-commit hooks - Solo validaciones locales ligeras
# Terraform/Ansible/Helm docs se generan en CI/CD

repos:
  # Utilidades generales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2048']

  # Nota: Las validaciones de Terraform se hacen en CI/CD
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.88.0
  #   hooks:
  #     - id: terraform_fmt
  #     - id: terraform_validate
