---
# meta/main.yml - Role metadata

galaxy_info:
  author: DevOps Team
  description: Install and configure NGINX web server
  company: Your Company
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - nginx
    - webserver
    - web

dependencies: []

allow_duplicates: false
